wandb_version: 1

batch_size:
  desc: null
  value: 16
conv_hid_size:
  desc: null
  value: 32
conv_in_size:
  desc: null
  value: 256
conv_out_size:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.2
fc_size:
  desc: null
  value: 64
hidden_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 1.0e-05
max_epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702524651.963504
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.4
      5: 0.16.1
      8:
      - 1
      - 5
      13: darwin-x86_64
