wandb_version: 1

batch_size:
  value: 16
conv_hid_size:
  value: 16
conv_in_size:
  value: 256
conv_out_size:
  value: 8
dropout:
  value: 0.4
fc_size:
  value: 128
hidden_size:
  value: 16
lr:
  value: 0.0001
max_epochs:
  value: 500
