wandb_version: 1

batch_size:
  value: 8
conv_hid_size:
  value: 16
conv_in_size:
  value: 256
conv_out_size:
  value: 8
dropout:
  value: 0.3
fc_size:
  value: 64
hidden_size:
  value: 16
lr:
  value: 1.0e-05
max_epochs:
  value: 5
