wandb_version: 1

batch_size:
  value: 48
conv_hid_size:
  value: 8
conv_in_size:
  value: 256
conv_out_size:
  value: 8
dropout:
  value: 0.3
fc_size:
  value: 64
hidden_size:
  value: 8
lr:
  value: 0.001
max_epochs:
  value: 5
