wandb_version: 1

batch_size:
  value: 16
conv_hid_size:
  value: 8
conv_in_size:
  value: 64
conv_out_size:
  value: 32
dropout:
  value: 0.2
fc_size:
  value: 32
hidden_size:
  value: 16
lr:
  value: 0.01
max_epochs:
  value: 5
