wandb_version: 1

batch_size:
  value: 16
conv_hid_size:
  value: 16
conv_in_size:
  value: 256
conv_out_size:
  value: 16
dropout:
  value: 0.3
fc_size:
  value: 256
hidden_size:
  value: 8
lr:
  value: 0.01
max_epochs:
  value: 500
