wandb_version: 1

batch_size:
  value: 16
conv_hid_size:
  value: 32
conv_in_size:
  value: 32
conv_out_size:
  value: 32
dropout:
  value: 0.3
fc_size:
  value: 32
hidden_size:
  value: 16
lr:
  value: 0.0001
max_epochs:
  value: 200
