wandb_version: 1

batch_size:
  value: 16
conv_hid_size:
  value: 16
conv_in_size:
  value: 64
conv_out_size:
  value: 32
dropout:
  value: 0.4
fc_size:
  value: 128
hidden_size:
  value: 8
lr:
  value: 0.001
max_epochs:
  value: 200
