wandb_version: 1

batch_size:
  value: 48
conv_hid_size:
  value: 8
conv_in_size:
  value: 64
conv_out_size:
  value: 8
dropout:
  value: 0.4
fc_size:
  value: 256
hidden_size:
  value: 16
lr:
  value: 0.001
max_epochs:
  value: 200
