wandb_version: 1

batch_size:
  value: 32
conv_hid_size:
  value: 16
conv_in_size:
  value: 32
conv_out_size:
  value: 32
dropout:
  value: 0.2
fc_size:
  value: 256
hidden_size:
  value: 8
lr:
  value: 1.0e-05
max_epochs:
  value: 200
